from pydantic import BaseModel, Field, EmailStr
from typing import Annotated

class Student(BaseModel):
    id: Annotated[int ,Field(..., description="AutoGenerated")]
    name: Annotated[str, Field(..., description="Name of the Student", examples=["John Doe"])]
    age: Annotated[int, Field(..., description="Age of the Student", examples=["19"], lt=120, gt=0)]
    grade: Annotated[str, Field(..., description="Grade of the Student", examples=["A", "B", "B+"])]
    email: Annotated[EmailStr, Field(...,description="email of the student", examples=["johndoe@gmail.com"])]

class StudentCreate(BaseModel):
    name: Annotated[str, Field(..., description="Name of the Student", examples=["John Doe"])]
    age: Annotated[int, Field(..., description="Age of the Student", examples=["19"], lt=120, gt=0)]
    grade: Annotated[str, Field(..., description="Grade of the Student", examples=["A", "B", "B+"])]
    email: Annotated[EmailStr, Field(...,description="email of the student", examples=["johndoe@gmail.com"])]

class StudentDelete(BaseModel):
    id: Annotated[int ,Field(..., description="AutoGenerated")]
    name: Annotated[str, Field(..., description="Name of the Student", examples=["John Doe"])]